name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  linux_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-20.04, ubuntu-22.04, ubuntu-latest,
          macos-11, macos-12, macos-13, macos-14, macos-latest,
        ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Build
        run: make DEBUG=1
      
      - name: Check
        run: make check
    
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, windows-2022, windows-latest ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Build
        run: ./build.bat
      
      - name: Check
        run: ./amalgamate -h
